### ISSUE TITLE
Depth Predictor 개발

### ISSUE THREAD

**Issue by gigio1023** [naem1023/Measuring-Image-Distance#6]
## Overview
https://github.com/naem1023/Measuring-Image-Distance/issues/1#issuecomment-830773385

## TODO
- [ ] MegaDepth 모델을 사용하여 임의의 이미지로부터 Depth 정보를 구하는 모듈 개발
  -  출력되는 이미지 사이즈는 일단 MegaDepth의 스펙을 따르기로 한다.

**Comment by pjongy** [comment]
https://github.com/naem1023/Measuring-Image-Distance/tree/megadepth/6-depth-predictor

demo.py에서 코드 생성
